<!DOCTYPE html>
<html <?php language_attributes(); ?>>

<head>
    <meta charset="<?php bloginfo('charset'); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php wp_head(); ?>
</head>

<body <?php body_class('font-sans'); ?>>
    <!-- Header section -->
    <div id="navbar"></div>

    <?php
    /**
     * Render the page content.
     * Since we have only the Hero section in the content, all the other contents are hard-coded below.
     */

    the_content();
    ?>

    <?php
    /**
     * This section is generated by a custom Gutenberg block, we don't need it anymore.
     *
    <!-- Hero section -->
    <section class="h-screen bg-black">
        <div class="flex h-full items-center relative">
            <div class="container mx-auto flex lg:block content-center h-full">
                <div class="bg-[#090A0B] bg-opacity-75 lg:bg-opacity-0 p-6 flex flex-1 flex-col justify-center lg:block w-full lg:ml-28 2xl:ml-0 lg:w-[30%] relative z-10">
                    <div>
                        <h1 class="text-[#FF2525] text-[32px] mb-4">Lorem ipsum dolor sit</h1>
                        <p class="text-white text-[22px] leading-[32px] mb-8">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus fermentum nec lacus eu imperdiet. Cras commodo.</p>
                        <p class="text-white text-[22px] leading-[32px] mb-4">Lorem ipsum dolor sit amet</p>
                        <a href="#apply" class="py-2 px-8 rounded bg-gradient-360 from-[#950000] from-[0.2%] to-[#FF2626] to-[99.8%] hover:from-[#FF2626] hover:to-[#950000] text-white">
                            Apply Now!
                        </a>
                    </div>
                </div>
            </div>
            <div class="w-full h-full absolute bg-cover bg-bottom bg-center bg-no-repeat" style="background-image: url('/wp-content/themes/dclr/images/Header_image.jpg')"></div>
        </div>
    </section>
     */
    ?>

    <!-- Section 1 -->
    <section class="text-white py-[72px] px-28 bg-center bg-cover bg-no-repeat" style="background-image: url('/wp-content/themes/dclr/images/Background.png');">
        <p class="container mx-auto text-center text-[20px] leading-[32px]">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus fermentum nec lacus eu imperdiet. Cras commodo purus tellus, id condimentum ipsum ultrices et. Nam eu risus in massa venenatis tempor in non nisl.<br />Nulla scelerisque, massa et blandit efficitur, neque turpis auctor ex, quis dapibus.</p>
    </section>

    <!-- Section 2 -->
    <section class="bg-[#090A0B] text-[#CDCDCD]">
        <div class="container mx-auto relative lg:px-8 lg:pb-[12rem] pt-[7rem]">
            <div class="relative z-10 px-8 lg:px-0 lg:w-[700px]">
                <h2 class="text-[32px] leading-[40px] font-bold relative after:absolute after:bottom-0 after:left-0 after:w-[80px] after:h-[2px] after:bg-[#FF2525] pb-8 mb-8">Lorem ipsum dolor sit amet, consectetur adipiscing elit ivamus fermentum nec lacus</h2>
                <div class="lg:pr-[160px]">
                    <p class="text-[22px] leading-[32px] mb-8">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus fermentum nec lacus eu imperdiet. Cras commodo purus tellus, id condimentum ipsum ultrices et. Nam eu risus in massa venenatis tempor in non nisl.</p>

                    <p class="text-[22px] leading-[32px] mb-8">Curabitur varius ut risus quis congue. Nulla scelerisque, massa et blandit efficitur, neque turpis auctor ex, quis dapibus arcu ligula nec urna. Curabitur nec rhoncus risus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>

                    <p class="text-[22px] leading-[32px] mb-8">Praesent erat nisl, aliquam egestas nunc sed, ornare tempus sem. Donec condimentum finibus eros, a rutrum ipsum consectetur eget. Aenean consequat eu metus nec pulvinar.</p>
                    </p>
                </div>
            </div>
            <div class="relative flex justify-items-end lg:absolute lg:h-full lg:w-full bottom-0 left-0 bg-cover bg-right-bottom bg-no-repeat"><img src="/wp-content/themes/dclr/images/Girl_image_1.png" class="object-cover" alt=""></div>
        </div>
    </section>

    <!-- Section 3 -->
    <section class="relative bg-[#090A0B] text-[#CDCDCD] pb-8 lg:pb-[12rem] pt-[7rem]">
        <div class="mb-28 container mx-auto px-8">
            <h2 class="text-[32px] leading-[40px] font-bold relative after:absolute after:bottom-0 after:left-0 after:w-[80px] after:h-[2px] after:bg-[#FF2525] pb-8 mb-8">Lorem ipsum dolor sit amet</h2>

            <p class="text-[22px] leading-[32px] mb-8">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus fermentum nec lacus eu imperdiet. Cras commodo purus tellus, id condimentum ipsum ultrices et. Nam eu risus in massa venenatis tempor in non nisl lacus eu.</p>

            <p class="text-[22px] leading-[32px] mb-8">Curabitur varius ut risus quis congue. Nulla scelerisque, massa et blandit efficitur, neque turpis auctor ex, quis dapibus arcu ligula nec urna. Curabitur nec rhoncus risus.</p>
        </div>

        <div class="container mx-auto mb-8 lg:mb-0 lg:flex items-center relative z-30 after:hidden lg:after:block after:w-[40px] after:h-[40px] after:absolute after:bottom-0 after:left-1/2 after:bg-[red] after:-ml-[20px] after:-mb-[20px] after:rounded">
            <div class="relative z-40 w-full lg:w-1/2 mb-8 lg:mb-0">
                <img src="/wp-content/themes/dclr/images/Becomeamodel_image_1.jpg" alt="" class="lg:rounded-r w-full" />
            </div>
            <div class="w-full lg:w-1/2 px-8 lg:px-12">
                <div class="lg:w-[512px]">
                    <h2 class="text-[32px] leading-[40px] relative after:absolute after:bottom-0 after:left-0 after:w-[80px] after:h-[2px] after:bg-[#FF2525] pb-8 mb-8">Lorem ipsum dolor sit amet</h2>
                    <p class="text-[22px] leading-[32px]">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus fermentum nec lacus eu imperdiet. Cras commodo purus tellus, id condimentum ipsum ultrices et.</p>
                </div>
            </div>
        </div>

        <div class="container mx-auto mb-8 lg:mb-0 lg:flex items-center relative z-20 after:hidden lg:after:block after:w-[40px] after:h-[40px] after:absolute after:bottom-0 after:left-1/2 after:bg-[red] after:-ml-[20px] after:-mb-[20px] after:rounded">
            <div class="relative z-40 w-full lg:w-1/2 mb-8 lg:mb-0 lg:order-2">
                <img src="/wp-content/themes/dclr/images/Becomeamodel_image_2.jpg" alt="" class="lg:rounded-l w-full" />
            </div>
            <div class="w-full lg:w-1/2 px-8 lg:px-12">
                <div class="lg:w-[512px]">
                    <h2 class="text-[32px] leading-[40px] relative after:absolute after:bottom-0 after:left-0 after:w-[80px] after:h-[2px] after:bg-[#FF2525] pb-8 mb-8">Lorem ipsum dolor sit amet</h2>
                    <p class="text-[22px] leading-[32px]">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus fermentum nec lacus eu imperdiet. Cras commodo purus tellus, id condimentum ipsum ultrices et.</p>
                </div>
            </div>
        </div>

        <div class="container mx-auto relative mb-8 lg:mb-0 lg:flex items-center">
            <div class="w-full lg:w-1/2 mb-8 lg:mb-0">
                <img src="/wp-content/themes/dclr/images/Becomeamodel_image_3.jpg" alt="" class="lg:rounded-r w-full" />
            </div>
            <div class="w-full lg:w-1/2 px-8 lg:px-12">
                <div class="lg:w-[512px]">
                    <h2 class="text-[32px] leading-[40px] relative after:absolute after:bottom-0 after:left-0 after:w-[80px] after:h-[2px] after:bg-[#FF2525] pb-8 mb-8">Lorem ipsum dolor sit amet</h2>
                    <p class="text-[22px] leading-[32px]">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus fermentum nec lacus eu imperdiet. Cras commodo purus tellus, id condimentum ipsum ultrices et.</p>
                </div>
            </div>
        </div>
    </section>

    <!-- Section 4 -->
    <section class="bg-[#090A0B] text-[#CDCDCD] pb-40">
        <div class="container mx-auto px-8 lg:px-0">
            <h2 class="text-white text-center text-[32px] leading-[40px] font-semibold mb-14">Lorem ipsum dolor sit amet</h2>

            <div class="flex flex-col md:flex-row md:justify-between lg:w-[936px] lg:mx-auto gap-16 relative">
                <div class="hidden lg:block absolute bg-red-100 h-[3px] w-3/5 top-[55px] absolute left-1/2 transform -translate-x-1/2"></div>
                <div>
                    <div class="relative z-10">
                        <img src="/wp-content/themes/dclr/images/svg/user.svg" alt="User" class="mx-auto mb-6 rounded-full bg-[#090A0B] p-[16px]" />
                    </div>
                    <h3 class="text-white text-center text-[22px] leading-[32px] font-bold mb-2">Lorem</h3>
                    <p class="text-base leading-normal text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus fermentum nec lacus eu imperdiet. Cras commodo purus tellus, id condimentum ipsum ultrices et.</p>
                </div>
                <div>
                    <div class="relative z-10">
                        <img src="/wp-content/themes/dclr/images/svg/cam.svg" alt="Camera" class="mx-auto mb-6 rounded-full bg-[#090A0B] p-[16px]" />
                    </div>
                    <h3 class="text-white text-center text-[22px] leading-[32px] font-bold mb-2">Lorem</h3>
                    <p class="text-base leading-normal text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus fermentum nec lacus eu imperdiet. Cras commodo purus tellus, id condimentum ipsum ultrices et.</p>
                </div>
                <div>
                    <div class="relative z-10">
                        <img src="/wp-content/themes/dclr/images/svg/money.svg" alt="Money" class="mx-auto mb-6 rounded-full bg-[#090A0B] p-[16px]" />
                    </div>
                    <h3 class="text-white text-center text-[22px] leading-[32px] font-bold mb-2">Lorem</h3>
                    <p class="text-base leading-normal text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus fermentum nec lacus eu imperdiet. Cras commodo purus tellus, id condimentum ipsum ultrices et.</p>
                </div>
            </div>
        </div>
    </section>

    <!-- Section 5 -->
    <section class="bg-[#090A0B] text-white pb-24 lg:pb-40 px-8 lg:px-28">
        <div class="container mx-auto">
            <h2 class="text-center text-[32px] leading-[40px] font-semibold mb-14">Lorem ipsum dolor sit amet</h2>

            <div class="md:w-full lg:mx-auto grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-8">
                <div class="mb-8 md:mb-0 px-8 bg-no-repeat bg-100 relative" style="background-image: url('/wp-content/themes/dclr/images/bricks.png')">
                    <div class="absolute top-0 left-0 w-full h-full bg-gradient-180 from-[rgba(0,0,0,0.0001)] via-[rgba(0,0,0,0.7764)] via-[48.13%] to-[#0A0A0D] to-[100%]"></div>
                    <div class="relative z-10 pb-8">
                        <div>
                            <img src="/wp-content/themes/dclr/images/svg/corset.svg" alt="" class="h-[104px] w-auto mx-auto mt-8 mb-6">
                        </div>
                        <h3 class="capitalize text-[22px] leading-[32px] font-bold mb-2 text-center">Lorem ipsum dolor sit</h3>
                        <p class="leading-normal text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus fermentum nec lacus eu imperdiet. Cras commodo purus tellus, id condimentum ipsum ultrices et lorem ipsum.</p>
                    </div>
                </div>
                <div class="mb-8 md:mb-0 px-8 bg-no-repeat bg-100 relative" style="background-image: url('/wp-content/themes/dclr/images/bricks.png')">
                    <div class="absolute top-0 left-0 w-full h-full bg-gradient-180 from-[rgba(0,0,0,0.0001)] via-[rgba(0,0,0,0.7764)] via-[48.13%] to-[#0A0A0D] to-[100%]"></div>
                    <div class="relative z-10">
                        <div>
                            <img src="/wp-content/themes/dclr/images/svg/dollar-bags.svg" alt="" class="h-[104px] w-auto mx-auto mt-8 mb-6">
                        </div>
                        <h3 class="capitalize text-[22px] leading-[32px] font-bold mb0b-2 text-center">Lorem ipsum dolor sit</h3>
                        <p class="leading-normal text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus fermentum nec lacus eu imperdiet. Cras commodo purus tellus, id condimentum ipsum ultrices et lorem ipsum.</p>
                    </div>
                </div>
                <div class="mb-8 md:mb-0 px-8 bg-no-repeat bg-100 relative" style="background-image: url('/wp-content/themes/dclr/images/bricks.png')">
                    <div class="absolute top-0 left-0 w-full h-full bg-gradient-180 from-[rgba(0,0,0,0.0001)] via-[rgba(0,0,0,0.7764)] via-[48.13%] to-[#0A0A0D] to-[100%]"></div>
                    <div class="relative z-10">
                        <div>
                            <img src="/wp-content/themes/dclr/images/svg/earnings.svg" alt="" class="h-[104px] w-auto mx-auto mt-8 mb-6">
                        </div>
                        <h3 class="capitalize text-[22px] leading-[32px] font-bold mb0b-2 text-center">Lorem ipsum dolor sit</h3>
                        <p class="leading-normal text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus fermentum nec lacus eu imperdiet. Cras commodo purus tellus, id condimentum ipsum ultrices et lorem ipsum.</p>
                    </div>
                </div>
                <div class="mb-8 md:mb-0 px-8 bg-no-repeat bg-100 relative" style="background-image: url('/wp-content/themes/dclr/images/bricks.png')">
                    <div class="absolute top-0 left-0 w-full h-full bg-gradient-180 from-[rgba(0,0,0,0.0001)] via-[rgba(0,0,0,0.7764)] via-[48.13%] to-[#0A0A0D] to-[100%]"></div>
                    <div class="relative z-10">
                        <div>
                            <img src="/wp-content/themes/dclr/images/svg/support.svg" alt="" class="h-[104px] w-auto mx-auto mt-8 mb-6">
                        </div>
                        <h3 class="capitalize text-[22px] leading-[32px] font-bold mb0b-2 text-center">Lorem ipsum dolor sit</h3>
                        <p class="leading-normal text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus fermentum nec lacus eu imperdiet. Cras commodo purus tellus, id condimentum ipsum ultrices et lorem ipsum.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Section 6 -->
    <section class="bg-[#090A0B] text-white">
        <div class="container mx-auto flex justify-end bg-no-repeat bg-left bg-cover lg:py-28" style="background-image: url('/wp-content/themes/dclr/images/Girl_image_2.jpg')">
            <div class="px-8 lg:px-0 lg:max-w-[515px] bg-[#090A0B] bg-opacity-70 md:bg-opacity-0 py-28">
                <h1 class="text-[32px] leading-[40px] font-semibold mb-8">Lorem ipsum dolor sit amet, consectetur adipi ipsum dolor sit</h1>
                <ul class="list-inside list-disc marker:text-[#FF2525]">
                    <li class="mb-8">Lorem ipsum dolor sit amet, consectetur adipi</li>
                    <li class="mb-8">Lorem ipsum dolor sit amet</li>
                    <li class="mb-8">Lorem ipsum dolor sit amet, consectetur adipi ipsum dolor sit</li>
                    <li class="mb-8">Lorem ipsum dolor sit</li>
                    <li>Lorem ipsum dolor sit amet, consectetur</li>
                </ul>
            </div>
        </div>
    </section>

    <!-- Section 7 -->
    <section class="flex bg-[#090A0B] md:min-h-[584px] bg-cover bg-no-repeat text-white border-b border-[#393939]" style="background-image: url('/wp-content/themes/dclr/images/Footer_image.jpg')">
        <div class="flex w-full items-center">
            <div class="py-24 px-8 md:py-0 md:px-0 lg:w-3/5 2xl:w-2/5 mx-auto text-center">
                <h2 class="text-center font-semibold text-[32px] leading-[40px] mb-10">Lorem ipsum dolor sit amet, consectetur adipiscing elit ivamus fermentum nec lacus!</h2>
                <a href="#apply" class="py-2 px-8 rounded bg-gradient-360 from-[#950000] from-[0.2%] to-[#FF2626] to-[99.8%] hover:from-[#FF2626] hover:to-[#950000] text-white">
                    Apply Now!
                </a>
            </div>
        </div>
    </section>

    <footer class="bg-[#090A0B] py-28">
        <div class="flex content-center max-w-[80%] md:max-w-[437px] mx-auto divide-x divide-[#FF2525]">
            <div class="w-1/2 pr-[20px] md:pr-[58px] flex items-center justify-end">
                <a href="/" class="text-white">
                    <span class="font-bold text-[40px] md:text-[58px] leading-[78px] uppercase">Logo</span>
                </a>
            </div>
            <div class="w-1/2 pl-[20px] md:pl-[58px]">
                <h3 class="font-bold text-sm text-[#FF2525] mb-3">Related Links</h3>
                <ul>
                    <li class="text-sm leading-loose"><a href="#" class="text-white hover:underline">Apply now!</a></li>
                    <li class="text-sm leading-loose"><a href="#" class="text-white hover:underline">F.A.Q</a></li>
                    <li class="text-sm leading-loose"><a href="#" class="text-white hover:underline">Contact</a></li>
                </ul>
            </div>
        </div>
    </footer>

    <?php wp_footer(); ?>
</body>

</html>
